---
version: '2'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
    volumes:
      - ./postgres/:/var/lib/postgresql/data/
    networks:
      - backend

  redis:
    image: redis:6.2.6
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/:/var/lib/redis/
    networks:
      - backend

  collabora:
    image: collabora/code:latest
    restart: always
    environment:
      - username=admin
      - password=${COLLABORA_PASSWORD}
      - domain=${COLLABORA_DOMAIN}
      - extra_params=--o:ssl.enable=true
    networks:
      - frontend

  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db
      - redis
      - code
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: applications_frontend
  backend:
