---
version: '2'

services:

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    links:
      - nextcloud
    networks:
      - frontend

networks:
  frontend:
    name: applications_frontend
    external: true